// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/hello": {
            "get": {
                "description": "token模板\n\"taosu *****.**************.************\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试"
                ],
                "summary": "你好",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer JWT-TOKEN",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data\",\"msg\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Description 登陆",
                "tags": [
                    "user"
                ],
                "summary": "登陆",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/signin": {
            "post": {
                "description": "Description 注册",
                "tags": [
                    "user"
                ],
                "summary": "注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/createitem": {
            "get": {
                "description": "Description 创建待办事项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "item_CRUD"
                ],
                "summary": "增",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer JWT-TOKEN",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "item",
                        "name": "item",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data\",\"msg\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/deleteitem": {
            "post": {
                "description": "Description 删除待办事项",
                "tags": [
                    "item_CRUD"
                ],
                "summary": "删",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer JWT-TOKEN",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "item",
                        "name": "item",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data\",\"msg\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/edititemstatus": {
            "post": {
                "description": "Description 修改待办事项状态",
                "tags": [
                    "item_CRUD"
                ],
                "summary": "改",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer JWT-TOKEN",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "item",
                        "name": "item",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "status",
                        "name": "status",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data\",\"msg\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/finditem": {
            "get": {
                "description": "Description 查询待办事项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "item_CRUD"
                ],
                "summary": "查",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer JWT-TOKEN",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data\",\"msg\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/test": {
            "get": {
                "description": "Description 创建待办事项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "item_CRUD"
                ],
                "summary": "测试",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer JWT-TOKEN",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data\",\"msg\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Taosuの备忘录demo",
	Description:      "用Hertz创建的简单备忘录demo.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
