mysql:
  dns: root:root@tcp(127.0.0.1:3306)/IM?charset=utf8mb4&parseTime=True&loc=Local
  username: root
  passwd: root
  host: 127.0.0.1
  port: 3306
  db: IM
  options:
    charset: utf8mb4
    parseTime: true
    loc: Local

redis:
  host: "127.0.0.1:6379"
  passwd: ""
  DB: 0
  poolSize: 30
  minIdleConn: 30