mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  db: blog
  charset: utf8mb4
  log_level: dev
system:
  host: "0.0.0.0"
  port: 2345
  env: release
logger:
  level: info
  prefix: '[blog]'
  director: log
  show_line: true
  log_in_console: true